### ISSUE TITLE
Help with Casual Path analysis

### ISSUE THREAD

**Issue by Maithy15** [PathwayAndDataAnalysis/causalpath#11]
Hi,

I am able to successfully run casual path analysis on the web server but have a few doubts. I have a dataset with three-time points and I provided the log fold change of the proteome and the phospho proteome as Input. Is it possible to make the casual path consider all three values for the analysis? When I upload to the webserver I just get the network figure. Is there a way to download any resulting data as a file? It would be great to know where casual path takes the info for each protein.

Thanks
Maithy

**Comment by ozgunbabur** [comment]
Hi Maithy, 

There are many options for CausalPath to interpret the values you have. In your case of fold changes, my preferred way would be to do 3 different analysis with the fold change of each case. But also you can tell CausalPath to use the average of these values (can be arithmetic or geometric mean). I don't know which makes more sense in your case.

The original webserver has an option to download the analysis result files. We have a new version of webserver but that download option is not there yet.

Let us know if you have more questions. We will gladly help you run the method if you need it.

**Comment by cannin** [comment]
@Maithy15 In case you are comfortable running command-line programs, we have written a detailed tutorial: 

https://www.sciencedirect.com/science/article/pii/S2666166721006614?via%3Dihub

**Comment by Maithy15** [comment]
Hi Ozgunbabur and Cannin,

Thanks for the help. I will first try the command-line version. I was a bit confused with the requirements of git and maven. I just need the casual path jar file, JDK, and chibe, right?

Thanks
Maithy

**Comment by cannin** [comment]
@Maithy15 To start off, as stated in the Star Protocols (https://www.sciencedirect.com/science/article/pii/S2666166721006614), there are only 2 required downloads:  

1. Download and install the Java 8 installation package from Oracle ([oracle.com/java](http://oracle.com/java)) or OpenJDK ([adoptopenjdk.net](http://adoptopenjdk.net/)); installers are provided for Windows, Linux, and MacOS. CausalPath has been tested with both Java 8 and 11 from Oracle or OpenJDK; it has been tested more thoroughly with Oracle Java 8.

2. Download the causalpath.jar file ([github.com/PathwayAndDataAnalysis/causalpath/releases](http://github.com/PathwayAndDataAnalysis/causalpath/releases)); version 1.2.0 is used for this protocol.

The word "maven" is not written in the Star Protocols walkthrough, so that should not be a concern.

**Comment by Maithy15** [comment]
Thanks for the reply. I already have java and downloaded the jar file, but nothing happens when I click on the icon. My java version is below.

 openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

Please let me know what I should do.

Thanks
Maithy

**Comment by cannin** [comment]
@Maithy15 Keep following the tutorial. Sounds like you are up to the "Run CausalPath" section. There is no clicking; you must type commands into a terminal.

**Comment by Maithy15** [comment]
Ah, Sorry, I thought it was a GUI, I will read through the star protocol paper!

**Comment by cannin** [comment]
@Maithy15 the website is the GUI, but to get the more details, you'll need to run the command-line program.

**Comment by Maithy15** [comment]
Hi Everyone!

I can successfully run the analysis. Sorry for the stupid questions. I do have some more questions regarding the analysis!

1. Which value is better? Signed P-values, fold change, or correlation?
2. Should the values for the protein reads or fold change be log-transformed or not? (I use Mass Spec data which are log2 transformed).
3. For the FDR/other thresholds, is there any standard value that works better, or is it simply based on the user?
4. What is the range for these thresholds 0-1?
5. Which commands from https://github.com/PathwayAndDataAnalysis/causalpath/blob/master/wiki/InputFormat.md work on version 1.2? For example, I tried to use the feature column initially, which gave an error. From the star protocol paper, it seems this is no longer needed.


Thanks
Maithy

**Comment by ozgunbabur** [comment]
Hi Maithy,

I am glad it is working now. Here are a few answers.

1. None of them is better. A comparison-based analysis can use signed p-values or fold-change. A correlation-based analysis will calculate correlations from the values you provide for each sample. If you want to control the FDR in a comparison-based analysis, then you need to prefer signed p-values over fold-change because we cannot control FDR with the fold-change.
2. For the protein reads, log transforming makes the noise more look like a Gaussian, so it is much preferable. For the fold change, it doesn't matter because you are providing a threshold. If you log transform the fold change, then you also need to adjust your threshold.
3. I generally go with 0.1 FDR cutoff and try smaller values if the result is very large.
4. It depends on this threshold we are talking about. If it is a p-value or FDR threshold, then it has to be between 0 and 1. If it is a value threshold, then it can be any positive number.
5. We introduced the Feature column recently. It is for integrating all data types in a single file. You can ignore it for version 1.2. Other parameters should work fine with v1.2.

**Comment by Maithy15** [comment]
Hi Babur,

Thanks for the quick reply. 

Cheers
Maithy

**Comment by Maithy15** [comment]
Hi Babur,

When I tried to use all the repositories for the analysis, I got the following exception. The analysis itself finishes but is this exception a problem?

java.io.FileNotFoundException: \home\babur\Documents\PC\SignedByTCGAConsensusFiltered.sif (The system cannot find the path specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(Unknown Source)
        at java.base/java.io.FileInputStream.<init>(Unknown Source)
        at java.base/java.io.FileInputStream.<init>(Unknown Source)
        at org.panda.utility.graph.Graph.load(Graph.java:49)
        at org.panda.causalpath.resource.NetworkLoader.load(NetworkLoader.java:86)
        at org.panda.causalpath.run.CausalPath.run(CausalPath.java:402)
        at org.panda.causalpath.run.CausalPath.main(CausalPath.java:286)
java.io.FileNotFoundException: \home\babur\Documents\PC\SignedByTCGAConsensusFiltered.sif (The system cannot find the path specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(Unknown Source)
        at java.base/java.io.FileInputStream.<init>(Unknown Source)
        at java.base/java.io.FileInputStream.<init>(Unknown Source)
        at org.panda.utility.graph.Graph.load(Graph.java:49)
        at org.panda.causalpath.resource.NetworkLoader.load(NetworkLoader.java:87)
        at org.panda.causalpath.run.CausalPath.run(CausalPath.java:402)
        at org.panda.causalpath.run.CausalPath.main(CausalPath.java:286)

Thanks
Maithy

**Comment by ozgunbabur** [comment]
Hi Maithy,

That is an experimental resource that wasn't supposed to be used by you. My suggestion is to stick with the default set of resources (meaning don't specify anything on the parameters). There are a few of these that will not work, even if they did, the results may be unreliable because of the nature of the resource. Safe resources are PC, PhosphoSitePlus, PhosphoNetworks, IPTMNet, TRRUST and TFactS. Those are also the default selection. All other resources have a problem of their own.

**Comment by yuxi-Zhao** [comment]
Hi,

I tried the Star Protocols (https://www.sciencedirect.com/science/article/pii/S2666166721006614) for the tutorial analysis but got the following exception. Is this a network problem? Just to confirm.
java.net.UnknownHostException: raw.githubusercontent.com
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
        at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
        at org.panda.resource.Download.downloadAsIs(Download.java:63)
        at org.panda.resource.FileServer.downloadResources(FileServer.java:72)
        at org.panda.resource.FileServer.init(FileServer.java:49)
        at org.panda.resource.FileServer.<init>(FileServer.java:37)
        at org.panda.resource.siteeffect.SiteEffectServer.<init>(SiteEffectServer.java:17)
        at org.panda.resource.siteeffect.PhosphoSitePlus.<init>(PhosphoSitePlus.java:17)
        at org.panda.resource.siteeffect.PhosphoSitePlus.get(PhosphoSitePlus.java:25)
        at org.panda.resource.tcga.ProteomicsFileRow.<init>(ProteomicsFileRow.java:42)
        at org.panda.causalpath.resource.ProteomicsFileReader.readAnnotation(ProteomicsFileReader.java:83)
        at org.panda.causalpath.run.CausalPath.run(CausalPath.java:354)
        at org.panda.causalpath.run.CausalPath.main(CausalPath.java:286)
Cannot download https://raw.githubusercontent.com/PathwayAndDataAnalysis/repo/master/resource-files/Regulatory_sites
Exception in thread "main" java.lang.RuntimeException: Cannot initialize the resource

Thanks

**Comment by ozgunbabur** [comment]
Hi Yuxi,

The error says it cannot download https://raw.githubusercontent.com/PathwayAndDataAnalysis/repo/master/resource-files/Regulatory_sites. What do you see when you click on that link from your browser? It works fine for me. If it doesn't work for you, then GitHub may be blocking access to your location.

**Comment by yuxi-Zhao** [comment]
Hi ozgunbabur

This link works fine for my browser when I use a VPN, but doesn't work for my Java (ㄒoㄒ)
