### ISSUE TITLE
getChangeSign can be called only after setting the change detector

### ISSUE THREAD

**Issue by DahhamAlsoud** [PathwayAndDataAnalysis/causalpath#28]
Hi! Thanks for making this nice tool available!

I'm trying to use CausalPath for RNAseq data using these parameters:
proteomics-values-file = xxx.txt
id-column = ID
symbols-column = Symbols
sites-column = Sites
effect-column = Effect
value-transformation = signed-p-values
value-column = Value
threshold-for-data-significance = 0.05 rna
calculate-network-significance = true
permutations-for-significance = 10000
fdr-threshold-for-network-significance = 0.05
use-network-significance-for-causal-reasoning = true
minimum-potential-targets-to-consider-for-downstream-significance = 10
color-saturation-value = 10
show-all-genes-with-proteomic-data = false
data-type-for-expressional-targets = rna
use-expression-for-activity-evidence = true

I left sites and effects empty

I receive this error:
Exception in thread "main" java.lang.RuntimeException: getChangeSign can be called only after setting the change detector.
        at org.panda.causalpath.data.ExperimentData.getChangeSign(ExperimentData.java:60)
        at org.panda.causalpath.analyzer.DataLabelShuffler.convert(DataLabelShuffler.java:134)
        at org.panda.causalpath.analyzer.DataLabelShuffler.convert(DataLabelShuffler.java:118)
        at org.panda.causalpath.analyzer.DataLabelShuffler.init(DataLabelShuffler.java:52)
        at org.panda.causalpath.analyzer.DataLabelShuffler.<init>(DataLabelShuffler.java:33)
        at org.panda.causalpath.analyzer.NSCForComparison.run(NSCForComparison.java:60)
        at org.panda.causalpath.run.CausalPath.calculateNetworkSignificance(CausalPath.java:777)
        at org.panda.causalpath.run.CausalPath.run(CausalPath.java:586)
        at org.panda.causalpath.run.CausalPath.main(CausalPath.java:317)

It seems that a "chDet" object should be initialized/assigned, but I couldn't find any further solution..

Any further guidance would be appreciated!

Thank you
Dahham

**Comment by ozgunbabur** [comment]
Hi Dahham,

The problem is that the software does not understand your data is RNAseq. There is a mechanism to designate the kind of omics of each data row. Add a "Feature" column to your data file and make it display "R" (without quotes, meaning the row is RNA measure) on each row. Then add the parameter "feature-column = Feature" in the parameters.txt file. 

Let me know if this resolves the issue.

Ozgun

**Comment by DahhamAlsoud** [comment]
Hi Ozgun,

Thank you very much for your prompt and kind answer!

Adding the "Feature" column as you described indeed resolved my issue!

Thank you very much!
Dahham
