### ISSUE TITLE
Make plotting optional

### ISSUE THREAD

**Issue by cannin** [PathwayAndDataAnalysis/causalpath#3]
This line: 

https://github.com/PathwayAndDataAnalysis/causalpath/blob/0e058301ee0482ea2727ed61b8d03d0cd698de29/src/main/java/org/panda/causalpath/analyzer/NSCForCorrelation.java#L130

Triggers the following error when running in an environment without X11:

Exception in thread "main" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at org.panda.utility.statistics.KernelDensityPlot.<init>(KernelDensityPlot.java:23)
	at org.panda.utility.statistics.KernelDensityPlot.plot(KernelDensityPlot.java:87)
	at org.panda.causalpath.analyzer.NSCForCorrelation.run(NSCForCorrelation.java:130)
	at org.panda.causalpath.run.CausalPath.calculateNetworkSignificance(CausalPath.java:594)
	at org.panda.causalpath.run.CausalPath.run(CausalPath.java:433)
	at org.panda.causalpath.run.CausalPath.main(CausalPath.java:247)

I don't think it ever actually gets shown to the user, anyways.

**Comment by ozgunbabur** [comment]
That is a debug code accidentally committed. Removed that a while ago.
