### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16

### ISSUE THREAD

**Issue by cannin** [PathwayAndDataAnalysis/causalpath#7]
What does this mean? How do I fix this problem? 

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
	at org.panda.causalpath.resource.ProteomicsFileReader.readAnnotation(ProteomicsFileReader.java:60)
	at org.panda.causalpath.run.CausalPath.run(CausalPath.java:354)
	at org.panda.causalpath.run.CausalPath.main(CausalPath.java:286)

**Comment by ozgunbabur** [comment]
Probably a column name in the parameter file does not match with the column name in the platform or values file.

**Comment by cannin** [comment]
Thanks. It looks like the names of columns "ID	Symbols	Sites	Effect" are case-sensitive.

**Comment by ozgunbabur** [comment]
They are case sensitive.
